import './globals.css'
import { Trirong } from 'next/font/google';
import "bootstrap/dist/css/bootstrap.css";

const trirong = Trirong({
  subsets: ['latin'],
  weight: [ "200"]
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={trirong.className}>{children}</body>
    </html>
  );
}
